name: Run unit tests with PHPUnit

on: [push]

jobs:
  phpunit-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        uses: php-actions/composer@v6
        with:
          php_version: 8.0
          command: validate

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.0
          args: --prefer-dist --no-progress --no-suggest

      - name: Run unit tests with PHPUnit
        uses: php-actions/composer@v6
        with:
          php_version: 8.0
          command: phpunit
